- id: '1642362108821'
  alias: 'Start Heater '
  description: ''
  trigger:
  - platform: state
    entity_id: input_boolean.heater
    from: 'off'
    to: 'on'
  condition: []
  action:
  - service: input_boolean.turn_off
    target:
      entity_id: input_boolean.cooler
  mode: single
- id: '1642362181462'
  alias: Start Coler
  description: ''
  trigger:
  - platform: state
    entity_id: input_boolean.cooler
    from: 'off'
    to: 'on'
  condition: []
  action:
  - service: input_boolean.turn_off
    target:
      entity_id: input_boolean.heater
  mode: single
- id: '1642362810960'
  alias: Start the heater relay
  description: ''
  trigger:
  - platform: state
    entity_id: input_boolean.heater
    from: 'off'
    to: 'on'
  condition: []
  action:
  - service: switch.turn_on
    target:
      entity_id: switch.heat
  - service: switch.turn_off
    target:
      entity_id: switch.cold
  - delay:
      hours: 0
      minutes: 1
      seconds: 0
      milliseconds: 0
  - service: switch.turn_off
    target:
      entity_id: switch.heat
  - delay:
      hours: 0
      minutes: 2
      seconds: 0
      milliseconds: 0
  - service: input_boolean.turn_off
    target:
      entity_id: input_boolean.heater
  mode: single
- id: '1642362896352'
  alias: Start the cooler relay
  description: ''
  trigger:
  - platform: state
    entity_id: input_boolean.cooler
    from: 'off'
    to: 'on'
  condition: []
  action:
  - service: switch.turn_on
    target:
      entity_id: switch.cold
  - service: switch.turn_off
    target:
      entity_id: switch.heat
  - delay:
      hours: 0
      minutes: 4
      seconds: 0
      milliseconds: 0
  - service: switch.turn_off
    target:
      entity_id: switch.cold
  - delay:
      hours: 0
      minutes: 3
      seconds: 0
      milliseconds: 0
  - service: input_boolean.turn_off
    target:
      entity_id: input_boolean.cooler
  mode: single
- id: '1642402919012'
  alias: 'Temp control: start heater'
  description: Temp control to start the heater when temp drops bellow set temp
  trigger:
  - platform: state
    entity_id: sensor.temp
    id: check temp heat
  condition:
  - condition: template
    value_template: '{{ states(''sensor.temp'') | float <  states(''input_number.temp'')
      | float - 2 }}'
  - condition: state
    entity_id: input_boolean.heater
    state: 'off'
  - condition: state
    entity_id: input_boolean.temp_control
    state: 'on'
  action:
  - service: input_boolean.turn_on
    target:
      entity_id: input_boolean.heater
  mode: single
- id: '1642405549474'
  alias: 'Temp control: start cooler'
  description: ''
  trigger:
  - platform: state
    entity_id: sensor.temp
    id: Check Temp
  condition:
  - condition: template
    value_template: '{{ states(''sensor.temp'') | float >  states(''input_number.temp'')
      | float +2 }}'
  - condition: state
    entity_id: input_boolean.cooler
    state: 'off'
  - condition: state
    entity_id: input_boolean.temp_control
    state: 'on'
  action:
  - service: input_boolean.turn_on
    target:
      entity_id: input_boolean.cooler
  mode: single
